### ISSUE TITLE
Calender on the main splash page

### ISSUE THREAD

**Issue by eparisi2009** [JeffVandenberg/wantonwicked#26]
It would be wonderful if the scene calender was on the main page for people to see activity on the site!

**Comment by JeffVandenberg** [comment]
What else should we have on the main page?

**Comment by eiragwen** [comment]
https://docs.google.com/spreadsheets/d/1j9xc4VZbl0co1EqNppz2x0wEJPsletV-2b8zBeHxAjQ/edit#gid=2092451577

**Comment by eparisi2009** [comment]
I made a suggested update what do you think?

Elizabeth Parisi
