### ISSUE TITLE
Dhampir Sheet

### ISSUE THREAD

**Issue by falco1029** [JeffVandenberg/wantonwicked#44]
We need a Dhampir Sheet so we can offer them as a character type. 
Copy the mortal sheet and make the following changes:
*Replace "Guild" with "Parent Clan" in Faction affiliations, and add "Covenant"
*Add Destiny as an Anchor
*If possible, have it autofill Thief of Fate (3 dots) and Omen Sensitivity (3 dots) in the Merit section. If not, nbd
*In abilities, add a "Themes" section, a "Twists" section, and a "Malisons" section

**Comment by AnneBSelcouth** [comment]
Dhampir's need an icon, I did this one as a possible.  Lemme know if you need it resized or anything
https://i.imgur.com/ezCIvE0.png

**Comment by JeffVandenberg** [comment]
I need two versions, one that's 32x23 and another that's 55x40. 

Examples: https://github.com/JeffVandenberg/wantonwicked/blob/master/webroot/chat/avatars/player.png

https://github.com/JeffVandenberg/wantonwicked/blob/master/webroot/chat/avatars/40/player.png

**Comment by AnneBSelcouth** [comment]
55X40: https://i.imgur.com/rvgWFtR.png
30X22: https://i.imgur.com/TBqpz2Z.png

**Comment by wyldepixie** [comment]
On the Dhampir sheets, the word in the dropdown under 'Type' is spelled incorrectly.
