### ISSUE TITLE
Request Closing themselves

### ISSUE THREAD

**Issue by AnneBSelcouth** [JeffVandenberg/wantonwicked#57]
So this is the request from CoinOperatedGirl, she said the ticket was closed and there is no note or anything form the staff.  Also included the issues SarahG and Larry talked about from tech channel
https://wantonwicked.gamingsandbox.com/requests/st-view/37205
**SarahGToday at 7:41 AM**
Seems like it might be a tech thing with these requests vanishing. Gummybear just submitted a request that said 

"IDK what happened to half of my requests that were approved that just vanished .However, I had two exceptional suxx, fashion 5 rings I crafted for autumn. She has turned them over to Autumn and she has requested they be put on her and Ryus sheet please. "

So that makes like...3 people who said requests vanished?

**LarryGToday at 8:04 AM**
One of mine vanished, after it was approved, too.

**Comment by JeffVandenberg** [comment]
THis is because anyone attached to a request can close the request. Need to work out what the logic of requests closing should look like.
