### ISSUE TITLE
Beast Sheet for 6.0

### ISSUE THREAD

**Issue by AnneBSelcouth** [JeffVandenberg/wantonwicked#61]
Jeff we need the beast sheet for the 6.0 game

**Comment by falco1029** [comment]
We also need a sheet for their half-template: Heralds. 
Basically it's a mortal sheet with Virtue/Vice replaced with Life/Legend, and a spot for their patron Beast (Like a ghoul's regnant, etc)

**Comment by JeffVandenberg** [comment]
Done. Release incoming.
