### ISSUE TITLE
Changeling contract tiers and affinities

### ISSUE THREAD

**Issue by SquirrelFu** [JeffVandenberg/wantonwicked#78]
Issue #63  has, for some reason, a second issue attached to it which I am filing here as a separate issue for clarity's sake (No pun intended). Changeing contact tiers do not save when set to royal, and secondarily there is no checkbox for noting a contract as affinity or not. Considering that this is useful information for staff, I would like to see the tier fixed and the affinity boxes added.

Thank you!

**Comment by JeffVandenberg** [comment]
Fixed.
