### ISSUE TITLE
Unable to view scenes using the scene calendar

### ISSUE THREAD

**Issue by AlRascala** [JeffVandenberg/wantonwicked#81]
When clicking on a scene in the scene calendar, every one past and future takes you to an internal error page. Found using Brave and Edge on Windows and Chrome on Mac.
![Scene calendar error](https://user-images.githubusercontent.com/59342454/73131819-b1b57800-4076-11ea-917c-ac602556b89b.PNG)

**Comment by AlRascala** [comment]
Error reported on Firefox and Safari as well.

**Comment by JeffVandenberg** [comment]
fixed.. cleared db cache. ugh forum update.
