### ISSUE TITLE
LaurenV unable to see char sheets 

### ISSUE THREAD

**Issue by AnneBSelcouth** [JeffVandenberg/wantonwicked#90]
Lauren cannot see full char sheets on her staff name, I've checked all the permissions and pretty sure I got everything right?  The stats show up blink on her side.

**Comment by AnneBSelcouth** [comment]
![image](https://user-images.githubusercontent.com/40880037/91593906-d710aa00-e915-11ea-9d95-c3d7171f9509.png)

**Comment by JeffVandenberg** [comment]
This was an issue with her browser setup. Not a code issue.
